server:
  port: 8085




spring:
  thymeleaf:
    # 开发环境禁用页面缓存
    cache: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates
    suffix: .html


#  jar存放的地址
jar:
    path: file:D:\app\lib-test\ab-test.jar


